Font typescript conversion
smartface/smartface-native pull request #179
Opened 2022-02-21 12:01 UTC by furkanarabaci

2022-02-21 14:39 UTC, cenkce requested changes

2022-02-21 14:39 UTC, cenkce commented on ui/font/index.ts
> +const Font: typeof AbstractFont = require(`./font.${Device.deviceOS.toLowerCase()}`).default;
Buraya type da eklemen lazim `type Font = AbstractFont `;

2022-02-22 08:50 UTC, furkanarabaci commented on ui/font/index.ts
> +const Font: typeof AbstractFont = require(`./font.${Device.deviceOS.toLowerCase()}`).default;
Fixed

2022-02-22 17:07 UTC, cenkce commented on .types/missings-ios.d.ts
> +  constructor(path: string | string);
`string | string` kalmis

2022-02-22 20:47 UTC, furkanarabaci commented on .types/missings-ios.d.ts
> +  constructor(path: string | string);
Fixed

2022-02-23 10:40 UTC, merged