feature: calldetection
smartface/smartface-native pull request #185
Opened 2022-02-22 09:19 UTC by alimoncul

2022-02-23 08:04 UTC, alimoncul commented
@cenkce updated

2022-02-24 07:19 UTC, cenkce requested changes

2022-02-24 07:19 UTC, cenkce commented on device/calldetection/calldetection.ios.ts
> +    const EventFunctions = {
remove

2022-02-24 07:21 UTC, cenkce requested changes

2022-02-24 07:21 UTC, cenkce commented on device/calldetection/calldetection.android.ts
> +    const EventFunctions = {
remove

2022-02-24 08:31 UTC, merged