feature: contacts
smartface/smartface-native pull request #186
Opened 2022-02-22 11:11 UTC by alimoncul

2022-02-22 16:54 UTC, cenkce requested changes

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  const phoneNumbers = [];
`phoneNumbers` tipini ekleyelim

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  const returnValue = {};
`returnValue ` tipini ekleyelim

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  returnValue['phoneNumber'] = phoneNumbers;
`returnValue.phoneNumber` seklinde kullanalim

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  returnValue['email'] = emailAddresses;
`returnValue. email ` seklinde kullanalim

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  returnValue['urlAddress'] = urlAddresses;
`returnValue. urlAddress` seklinde kullanalim

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  returnValue['address'] = addresses;
bu da yukaridakiler gibi

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  getAll(params) {
`params: {onFailure: (error: any)=>void, onSuccess: ()=>void}

2022-02-22 16:54 UTC, cenkce commented on device/contacts/contacts.ts
> +      onSuccess: (contacts: ContactBase[]) => void;
`ContactBase` herzaman interface kullanmayi tercih edelim

2022-02-23 11:24 UTC, alimoncul commented
@cenkce updated, contactBase sart cunku static class var icinde `new Contacts.Contact()`

2022-02-24 07:10 UTC, cenkce requested changes

2022-02-24 07:10 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  add(params) {
params tipini verelim

2022-02-24 07:10 UTC, cenkce commented on device/contacts/contacts.ios.ts
> +  pick(params) {
params tipini verelim

2022-02-24 07:45 UTC, alimoncul commented on device/contacts/contacts.ios.ts
> +function manageNativeContact(contact) {
bu ios nativeobject contact tipi. bizim class degil

2022-02-24 08:27 UTC, merged