AlertView Typescript Conversion
smartface/smartface-native pull request #190
Opened 2022-02-22 17:00 UTC by furkanarabaci

2022-02-22 17:19 UTC, cenkce requested changes

2022-02-22 17:19 UTC, cenkce commented on ui/alertview/alertview.ios.ts
> +  constructor(params: Partial<AlertViewIOS> = {}) {
`Partial<AlertViewIOS>` => `Partial<IAlertView>`

2022-02-22 17:19 UTC, cenkce commented on ui/alertview/alertview.ts
> +  constructor(params?: Partial<AbstractAlertView>);
`Partial< AbstractAlertView >` => `Partial<IAlertView>`

2022-02-22 17:19 UTC, cenkce commented on ui/alertview/alertview.android.ts
> +  constructor(params: Partial<AlertViewAndroid> = {}) {
`Partial< AlertViewAndroid >` => `Partial<IAlertView>`

2022-02-22 20:44 UTC, furkanarabaci commented on ui/alertview/alertview.ios.ts
> +  constructor(params: Partial<AlertViewIOS> = {}) {
fixed

2022-02-22 20:44 UTC, furkanarabaci commented on ui/alertview/alertview.ts
> +  constructor(params?: Partial<AbstractAlertView>);
fixed

2022-02-22 20:44 UTC, furkanarabaci commented on ui/alertview/alertview.android.ts
> +  constructor(params: Partial<AlertViewAndroid> = {}) {
fixed

2022-02-23 08:46 UTC, cenkce requested changes

2022-02-23 08:46 UTC, cenkce commented on ui/alertview/alertview.ts
> +  onDismiss: (alertView?: AbstractAlertView) => void;
AbstractAlertView yerine IAlertView kullanalim

2022-02-23 12:55 UTC, furkanarabaci commented on ui/alertview/alertview.ts
> +  onDismiss: (alertView?: AbstractAlertView) => void;
fixed

2022-02-24 06:54 UTC, merged