Update gifimage to TypeScript
smartface/smartface-native pull request #196
Opened 2022-02-23 12:18 UTC by berkbaski

2022-02-23 16:33 UTC, cenkce requested changes

2022-02-23 16:33 UTC, cenkce commented on ui/gifimage/gifimage.android.ts
> +  get instrinsicSize(): { width: number; height: number } {
`{ width: number; height: number }` yerine Size kullanabilirsin

2022-02-23 16:33 UTC, cenkce commented on ui/gifimage/index.ts
> +  instrinsicSize: { width: number; height: number };
{ width: number; height: number } => Size

2022-02-23 16:33 UTC, cenkce commented on ui/gifimage/index.ts
> +  get instrinsicSize(): { width: number; height: number } {
Size

2022-02-24 09:45 UTC, berkbaski commented
Could you recheck again? @cenkce

2022-02-24 12:16 UTC, merged