feature: tabbar item
smartface/smartface-native pull request #211
Opened 2022-02-24 14:35 UTC by alimoncul

2022-02-24 17:16 UTC, cenkce requested changes

2022-02-24 17:16 UTC, cenkce commented on ui/tabbaritem/tabbaritem.android.ts
> +    const android = {
buna gerek yok `this._android` kullanalim burada

2022-02-24 17:16 UTC, cenkce commented on ui/tabbaritem/tabbaritem.android.ts
> +    Object.assign(this._android, android);
Bunu kaldirabiliriz gerek yok

2022-02-24 17:16 UTC, cenkce commented on ui/tabbaritem/tabbaritem.ios.ts
> +  private _ios: Partial<{ font: AbstractFont }>;
`{ font: AbstractFont }` bu implement edilmemis

2022-02-25 06:03 UTC, alimoncul commented
@cenkce updated

2022-02-25 06:25 UTC, cenkce requested changes

2022-02-25 06:25 UTC, cenkce commented on ui/tabbaritem/tabbaritem.ios.ts
> +  private _ios: Partial<{ font: Font }>;
remove _ios

2022-02-25 07:05 UTC, cenkce requested changes

2022-02-25 07:05 UTC, cenkce commented on ui/tabbaritem/tabbaritem.android.ts
> +      for (const param in params) {
bununla degistirelim
```const {ios, android, ...restParams} = params;
Object.assign(this.ios, ios);
Object.assign(this.android, android);
Object.assign(this, restParams);```

2022-02-25 07:05 UTC, cenkce commented on ui/tabbaritem/tabbaritem.ios.ts
> +    for (const param in params) {
```const {ios, android, ...restParams} = params;
Object.assign(this.ios, ios);
Object.assign(this.android, android);
Object.assign(this, restParams);```
bununla degistirelim

2022-02-28 11:06 UTC, cenkce requested changes

2022-02-28 11:06 UTC, cenkce commented on ui/tabbaritem/tabbaritem.android.ts
> +    const self = this;
Object.assign lari en altta yapalim

2022-02-28 13:24 UTC, merged