Update rangeslider to TypeScript
smartface/smartface-native pull request #212
Opened 2022-02-24 15:15 UTC by berkbaski

2022-02-24 17:28 UTC, cenkce requested changes

2022-02-24 17:28 UTC, cenkce commented on ui/rangeslider/rangeslider.ios.ts
> +    const EventFunctions = {
bunu kaldiralim gerek yok

2022-02-24 17:28 UTC, cenkce commented on ui/rangeslider/rangeslider.ios.ts
> +    eventCallbacksAssign(this, EventFunctions);
buna da gerek yok

2022-02-24 17:28 UTC, cenkce commented on ui/rangeslider/rangeslider.ios.ts
> +    const valueChangeHandler = () => {
`this.emit(RangeSliderEvents.ValueChange)` ekleyelim

2022-02-24 17:28 UTC, cenkce commented on ui/rangeslider/rangeslider.android.ts
> +      [RangeSliderEvents.ValueChange]: (e) => {
`EventFunctions`  bunu kaldiralim

2022-02-24 17:28 UTC, cenkce commented on ui/rangeslider/rangeslider.android.ts
> +
`this.nativeObject.setOnValueChange(() => {
  this.emit(RangeSliderEvents.ValueChange);
  this.onValueChange?.(e);
})`
ekleyelim

2022-02-25 06:58 UTC, berkbaski commented
Could you check it again? @cenkce

2022-02-28 10:51 UTC, cenkce requested changes

2022-02-28 10:51 UTC, cenkce commented on ui/rangeslider/rangeslider.ios.ts
> +    this.setParams(params);
`    this.setParams(params);
` kaldiralim

2022-02-28 10:51 UTC, cenkce commented on ui/rangeslider/rangeslider.ios.ts
> +  setParams(params: Partial<IRangeSlider>) {
setParams kaldiralim

2022-02-28 10:51 UTC, cenkce commented on ui/rangeslider/rangeslider.ios.ts
> +  setOSSpecificParams(params: Partial<IRangeSlider>, key: string) {
setOSSpecificParams kaldiralim

2022-03-07 07:45 UTC, berkbaski commented
I added `WithMobileOSProps` Could you recheck again? @cenkce

2022-03-08 10:15 UTC, merged