feature: livemediaplayer
smartface/smartface-native pull request #213
Opened 2022-02-24 16:08 UTC by alimoncul

2022-02-24 17:32 UTC, cenkce requested changes

2022-02-24 17:32 UTC, cenkce commented on ui/livemediaplayer/livemediaplayer.android.ts
> +    const EventFunctions = {
kaldiralim

2022-02-24 17:32 UTC, cenkce commented on ui/livemediaplayer/livemediaplayer.android.ts
> +    eventCallbacksAssign(this, EventFunctions);
kaldiralim

2022-02-24 17:32 UTC, cenkce commented on ui/livemediaplayer/livemediaplayer.ios.ts
> +      [LiveMediaPlayerEvents.Change]: function (state) {
kaldiralim

2022-02-24 17:32 UTC, cenkce commented on ui/livemediaplayer/livemediaplayer.ios.ts
> +    eventCallbacksAssign(this, EventFunctions);
kaldiralim

2022-02-25 06:08 UTC, alimoncul commented
@cenkce updated

2022-02-25 06:34 UTC, merged