Update switch to TypeScript
smartface/smartface-native pull request #217
Opened 2022-02-25 04:43 UTC by berkbaski

2022-02-25 07:01 UTC, berkbaski commented
Could you check it again? @cenkce

2022-02-28 10:40 UTC, cenkce requested changes

2022-02-28 10:40 UTC, cenkce commented on ui/switch/switch.ios.ts
> +    for (const param in params) {
burayi kaldiralim

2022-02-28 10:40 UTC, cenkce commented on ui/switch/switch.ios.ts
> +    super();
params gonderelim

2022-02-28 10:40 UTC, cenkce commented on ui/switch/switch.android.ts
> +    for (const param in params) {
burayi kaldiralim

2022-03-07 07:45 UTC, berkbaski commented
I added `WithMobileOSProps` Could you recheck again? @cenkce

2022-03-08 12:19 UTC, merged