Update GifImageView to TypeScript
smartface/smartface-native pull request #226
Opened 2022-02-25 12:29 UTC by berkbaski

2022-02-28 09:34 UTC, cenkce requested changes

2022-02-28 09:34 UTC, cenkce commented on ui/gifimageview/gifimageview.android.ts
> +    Object.assign(this, params);
bunu kaldirip params super uzerinden gonderelim

2022-02-28 09:34 UTC, cenkce commented on ui/gifimageview/gifimageview.ios.ts
> +    Object.assign(this, params);
burada da ayni seklide super'i kullanalim

2022-03-02 07:17 UTC, berkbaski commented
I fixed the change requests. Could you check again? @cenkce

2022-03-07 08:37 UTC, merged