Update SearchView to TypeScript
smartface/smartface-native pull request #231
Opened 2022-02-28 12:29 UTC by berkbaski

2022-02-28 12:52 UTC, cenkce requested changes

2022-02-28 12:52 UTC, cenkce commented on ui/searchview/searchview.android.ts
> +    Object.assign(this.android, this.androidProps);
Object.assign(this._android, this.androidProps, android);

2022-02-28 12:52 UTC, cenkce commented on ui/searchview/searchview.android.ts
> +    Object.assign(this.ios, ios);
bunu kaldiralim ios'a default deger verelim {} olarak

2022-02-28 12:52 UTC, cenkce commented on ui/searchview/searchview.ios.ts
> +    Object.assign(this.ios, this.iOSProps);
Object.assign(this._ios, this.iOSProps);

2022-02-28 12:52 UTC, cenkce commented on ui/searchview/searchview.ios.ts
> +    Object.assign(this.android, {});
burayi kaldiralim

2022-03-02 07:21 UTC, berkbaski commented
I fixed the requests. Could you check it again? @cenkce

2022-03-07 19:57 UTC, merged